### ISSUE TITLE
Why an ES Module?

### ISSUE THREAD

**Issue by caprico-codes** [dmitriym09/stream-storage#5]
I found your library the other day and I think it is perfect for a use case I have in my future project. I am streaming data between socket.io clients where socket.io server acts as a middleman and caching centre. I use stream storage to cache the stream during transmission. The only question I have is why is it an ES module? I am pretty new to ES modules and instantly faced an error telling me to use an import instead of require. Furthermore I need to use ```"type" : "module"``` in package.json and ```experimental flag``` unless its ```node v13.9.0``` and above.

Sorry if I don't understand enough about ES modules, I am learning more each day. And thanks for the module, it abstracted away a lot of server code.

**Comment by dmitriym09** [comment]
ES module - modern and safety variant js-modules, with default strict mode and async loading. I like ES modules syntax. I try to use the latest version NodeJS with modern syntax. If you need a CommonJS module in this packet - I can add it.

Thanks for the feedback!

**Comment by caprico-codes** [comment]
@dmitriym09 Hey thanks for the CommonJS module offer. However its not a big problem for me as its server side code and I don't need to care about backward compatibility.

So I am closing this issue. Good day!
